In [1]:

from tensorflow.keras.preprocessing.text import one_hot # type: ignore|

In [3]:
# sentence

sent= [
    'the glass of milk',
    'the glass of juice',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [4]:
# Define the vocabulary size
vocab_size =10000

In [5]:
## One hot Representation
one_hot_repr = [one_hot(words ,vocab_size) for words in sent]
one_hot_repr

[[7960, 1446, 5444, 2618],
 [7960, 1446, 5444, 9256],
 [7566, 5024, 5249, 8003, 6662],
 [7566, 5024, 5249, 8003, 6056],
 [5091, 7960, 451, 5444, 1880],
 [1081, 3185, 7811, 8003]]

In [6]:
# word embedding representation

from tensorflow.keras.layers import Embedding # type: ignore
from tensorflow.keras.preprocessing.sequence import pad_sequences # type: ignore
from tensorflow.keras.models import Sequential # type: ignore

In [7]:
import numpy as np

In [8]:
sent_length =8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 7960 1446 5444 2618]
 [   0    0    0    0 7960 1446 5444 9256]
 [   0    0    0 7566 5024 5249 8003 6662]
 [   0    0    0 7566 5024 5249 8003 6056]
 [   0    0    0 5091 7960  451 5444 1880]
 [   0    0    0    0 1081 3185 7811 8003]]


In [9]:
# feature representation
dim = 10


In [13]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

In [17]:
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[[-3.83308530e-02,  1.31283291e-02,  1.73932053e-02,
          2.78305747e-02,  2.15204619e-02, -1.01241842e-02,
          4.37583663e-02, -3.42911482e-03, -1.13190413e-02,
          4.36589234e-02],
        [-3.83308530e-02,  1.31283291e-02,  1.73932053e-02,
          2.78305747e-02,  2.15204619e-02, -1.01241842e-02,
          4.37583663e-02, -3.42911482e-03, -1.13190413e-02,
          4.36589234e-02],
        [-3.83308530e-02,  1.31283291e-02,  1.73932053e-02,
          2.78305747e-02,  2.15204619e-02, -1.01241842e-02,
          4.37583663e-02, -3.42911482e-03, -1.13190413e-02,
          4.36589234e-02],
        [-3.83308530e-02,  1.31283291e-02,  1.73932053e-02,
          2.78305747e-02,  2.15204619e-02, -1.01241842e-02,
          4.37583663e-02, -3.42911482e-03, -1.13190413e-02,
          4.36589234e-02],
        [ 3.91239561e-02,  2.66625173e-02,  2.72456519e-02,
         -3.46649438e-04,  4.28800099e-02,  4.20317762e-02,
          2.91877724e-02,  1.75185241e-02, -2.034955

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 7960, 1446, 5444, 2618], dtype=int32)

In [27]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[[-0.03833085,  0.01312833,  0.01739321,  0.02783057,
          0.02152046, -0.01012418,  0.04375837, -0.00342911,
         -0.01131904,  0.04365892],
        [-0.03833085,  0.01312833,  0.01739321,  0.02783057,
          0.02152046, -0.01012418,  0.04375837, -0.00342911,
         -0.01131904,  0.04365892],
        [-0.03833085,  0.01312833,  0.01739321,  0.02783057,
          0.02152046, -0.01012418,  0.04375837, -0.00342911,
         -0.01131904,  0.04365892],
        [-0.03833085,  0.01312833,  0.01739321,  0.02783057,
          0.02152046, -0.01012418,  0.04375837, -0.00342911,
         -0.01131904,  0.04365892],
        [ 0.03912396,  0.02666252,  0.02724565, -0.00034665,
          0.04288001,  0.04203178,  0.02918777,  0.01751852,
         -0.02034955, -0.04155452],
        [-0.03528466, -0.04635031, -0.00505123,  0.04288146,
          0.01165488,  0.03035365,  0.01038239, -0.01666097,
          0.03618069,  0.04999759],
        [-0.04386873,  0.00506169,  0.0156271 , -0.0